name: Enforce Jira ID in Commit Messages
on: [push]  # Runs on every push and pull request

jobs:
  check-commits:
   runs-on: ubuntu-latest

    steps:
     - name: Checkout code
        uses: actions/checkout@v3
        
     - name: Get commit messages1
         run: |
          JIRA_REGEX="([A-Z]+-[0-9]+)"
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')

          # Ignore commits made by GitHub Actions
          if [[ "$AUTHOR" == "github-actions[bot]" ]]; then
            echo "✅ Skipping commit by GitHub Actions"
            exit 0
          fi

          # Check if the commit message contains a Jira ID
          if ! echo "$MESSAGE" | grep -qE "$JIRA_REGEX"; then
            echo "❌ ERROR: Commit message must include a Jira ID (e.g., ABC-123)"
            exit 1
          fi
